extends Node

# this file is auto generated by GDCastledb @arlez80
# DO NOT EDIT BY MANUAL

class ItemIndex extends CastleDB:

	class Row:
		var id := ""
		var _unique_id_name := ""
		var iname := ""
		var img_path := ""
		var slot := 0
		var equippable := false
		var menu_use := false
		var have_multiple := false
		var description := ""
		var instruction := ""
		func _init(_id:String,_iname:String,_img_path:String,_slot:int,_equippable:bool,_menu_use:bool,_have_multiple:bool,_description:String,_instruction:String):
			self._unique_id_name = _id
			self.id = _id
			self.iname = _iname
			self.img_path = _img_path
			self.slot = _slot
			self.equippable = _equippable
			self.menu_use = _menu_use
			self.have_multiple = _have_multiple
			self.description = _description
			self.instruction = _instruction
		func _delay_set_reference( import_src ):
			pass

	func _init( ):
		self.all = [ItemIndex.Row.new("notepad","Notepad","res://Sprite/Items/Notepad.png",0,false,true,false,"A detective's best friend.","Select it to save the game."),ItemIndex.Row.new("badge","Badge","res://Sprite/Items/Badge.png",1,false,true,false,"Definitive proof that you are Detective Amelia Watson. Your accomplishments are listed inside.",""),ItemIndex.Row.new("gear_case","Gear Part Case","res://Sprite/Items/GearPartCase.png",2,false,false,false,"A container to store gear fragments.","Collect 4 fragments to restore a gear in the pocket watch."),ItemIndex.Row.new("gun","Gun","res://Sprite/Items/Gun.png",3,false,false,false,"Your trusty revolver.",""),ItemIndex.Row.new("scroll","Counter Spell","res://Sprite/Items/Scroll.png",4,false,false,true,"Magic incantations left behind by The Ancient Ones. ","They can dispell purple barriers. Each scroll disintegrates after a single use.")]
		self._generate_keys( )

	func get_value( id:String ) -> ItemIndex.Row:
		if self.keys.has( id ):
			return self.all[self.keys[id]]
		return null

	func get_index( id:String ) -> int:
		if self.keys.has( id ):
			return self.keys[id]
		return -1

var table_item_index: = ItemIndex.new( )

func _init( ):
	self.table_item_index._delay_set_reference( self )
